/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectsNewRouteImport } from './routes/objects.new'
import { Route as ObjectsIdRouteImport } from './routes/objects.$id'
import { Route as EExperimentIdRouteImport } from './routes/e.$experimentId'
import { Route as ApiRelationshipsRouteImport } from './routes/api/relationships'
import { Route as ApiObjectsRouteImport } from './routes/api/objects'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGraphRouteImport } from './routes/api/graph'
import { Route as ApiExperimentsRouteImport } from './routes/api/experiments'
import { Route as ApiBrandingRouteImport } from './routes/api/branding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedExperimentsRouteImport } from './routes/_authenticated/experiments'
import { Route as EExperimentIdIndexRouteImport } from './routes/e.$experimentId.index'
import { Route as AuthenticatedExperimentsIndexRouteImport } from './routes/_authenticated/experiments.index'
import { Route as ApiPublicBrandingRouteImport } from './routes/api/public/branding'
import { Route as ApiObjectsIdRouteImport } from './routes/api/objects.$id'
import { Route as ApiExperimentsIdRouteImport } from './routes/api/experiments.$id'
import { Route as ApiBrandingUploadUrlRouteImport } from './routes/api/branding.upload-url'
import { Route as AuthenticatedExperimentsIdRouteImport } from './routes/_authenticated/experiments.$id'
import { Route as EExperimentIdSTokenRouteImport } from './routes/e.$experimentId.s.$token'
import { Route as ApiPublicSessionsTokenRouteImport } from './routes/api/public/sessions.$token'
import { Route as ApiPublicExperimentsIdRouteImport } from './routes/api/public/experiments.$id'
import { Route as ApiExperimentsIdStimuliRouteImport } from './routes/api/experiments.$id.stimuli'
import { Route as ApiExperimentsIdSessionsRouteImport } from './routes/api/experiments.$id.sessions'
import { Route as ApiExperimentsIdResultsRouteImport } from './routes/api/experiments.$id.results'
import { Route as ApiExperimentsIdPublishRouteImport } from './routes/api/experiments.$id.publish'
import { Route as ApiExperimentsIdDuplicateRouteImport } from './routes/api/experiments.$id.duplicate'
import { Route as ApiExperimentsIdCloseRouteImport } from './routes/api/experiments.$id.close'
import { Route as ApiPublicSessionsTokenResponsesRouteImport } from './routes/api/public/sessions.$token.responses'
import { Route as ApiPublicSessionsTokenConsentRouteImport } from './routes/api/public/sessions.$token.consent'
import { Route as ApiPublicSessionsTokenCompleteRouteImport } from './routes/api/public/sessions.$token.complete'
import { Route as ApiPublicExperimentsIdSessionsRouteImport } from './routes/api/public/experiments.$id.sessions'
import { Route as ApiExperimentsIdStimuliUploadUrlRouteImport } from './routes/api/experiments.$id.stimuli.upload-url'
import { Route as ApiExperimentsIdStimuliStimulusIdRouteImport } from './routes/api/experiments.$id.stimuli.$stimulusId'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsNewRoute = ObjectsNewRouteImport.update({
  id: '/objects/new',
  path: '/objects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdRoute = ObjectsIdRouteImport.update({
  id: '/objects/$id',
  path: '/objects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EExperimentIdRoute = EExperimentIdRouteImport.update({
  id: '/e/$experimentId',
  path: '/e/$experimentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelationshipsRoute = ApiRelationshipsRouteImport.update({
  id: '/api/relationships',
  path: '/api/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObjectsRoute = ApiObjectsRouteImport.update({
  id: '/api/objects',
  path: '/api/objects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphRoute = ApiGraphRouteImport.update({
  id: '/api/graph',
  path: '/api/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExperimentsRoute = ApiExperimentsRouteImport.update({
  id: '/api/experiments',
  path: '/api/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandingRoute = ApiBrandingRouteImport.update({
  id: '/api/branding',
  path: '/api/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperimentsRoute =
  AuthenticatedExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EExperimentIdIndexRoute = EExperimentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EExperimentIdRoute,
} as any)
const AuthenticatedExperimentsIndexRoute =
  AuthenticatedExperimentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const ApiPublicBrandingRoute = ApiPublicBrandingRouteImport.update({
  id: '/api/public/branding',
  path: '/api/public/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObjectsIdRoute = ApiObjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiObjectsRoute,
} as any)
const ApiExperimentsIdRoute = ApiExperimentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiExperimentsRoute,
} as any)
const ApiBrandingUploadUrlRoute = ApiBrandingUploadUrlRouteImport.update({
  id: '/upload-url',
  path: '/upload-url',
  getParentRoute: () => ApiBrandingRoute,
} as any)
const AuthenticatedExperimentsIdRoute =
  AuthenticatedExperimentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedExperimentsRoute,
  } as any)
const EExperimentIdSTokenRoute = EExperimentIdSTokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => EExperimentIdRoute,
} as any)
const ApiPublicSessionsTokenRoute = ApiPublicSessionsTokenRouteImport.update({
  id: '/api/public/sessions/$token',
  path: '/api/public/sessions/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExperimentsIdRoute = ApiPublicExperimentsIdRouteImport.update({
  id: '/api/public/experiments/$id',
  path: '/api/public/experiments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExperimentsIdStimuliRoute = ApiExperimentsIdStimuliRouteImport.update({
  id: '/stimuli',
  path: '/stimuli',
  getParentRoute: () => ApiExperimentsIdRoute,
} as any)
const ApiExperimentsIdSessionsRoute =
  ApiExperimentsIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ApiExperimentsIdRoute,
  } as any)
const ApiExperimentsIdResultsRoute = ApiExperimentsIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ApiExperimentsIdRoute,
} as any)
const ApiExperimentsIdPublishRoute = ApiExperimentsIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => ApiExperimentsIdRoute,
} as any)
const ApiExperimentsIdDuplicateRoute =
  ApiExperimentsIdDuplicateRouteImport.update({
    id: '/duplicate',
    path: '/duplicate',
    getParentRoute: () => ApiExperimentsIdRoute,
  } as any)
const ApiExperimentsIdCloseRoute = ApiExperimentsIdCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => ApiExperimentsIdRoute,
} as any)
const ApiPublicSessionsTokenResponsesRoute =
  ApiPublicSessionsTokenResponsesRouteImport.update({
    id: '/responses',
    path: '/responses',
    getParentRoute: () => ApiPublicSessionsTokenRoute,
  } as any)
const ApiPublicSessionsTokenConsentRoute =
  ApiPublicSessionsTokenConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => ApiPublicSessionsTokenRoute,
  } as any)
const ApiPublicSessionsTokenCompleteRoute =
  ApiPublicSessionsTokenCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiPublicSessionsTokenRoute,
  } as any)
const ApiPublicExperimentsIdSessionsRoute =
  ApiPublicExperimentsIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ApiPublicExperimentsIdRoute,
  } as any)
const ApiExperimentsIdStimuliUploadUrlRoute =
  ApiExperimentsIdStimuliUploadUrlRouteImport.update({
    id: '/upload-url',
    path: '/upload-url',
    getParentRoute: () => ApiExperimentsIdStimuliRoute,
  } as any)
const ApiExperimentsIdStimuliStimulusIdRoute =
  ApiExperimentsIdStimuliStimulusIdRouteImport.update({
    id: '/$stimulusId',
    path: '/$stimulusId',
    getParentRoute: () => ApiExperimentsIdStimuliRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system': typeof SystemRoute
  '/experiments': typeof AuthenticatedExperimentsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/branding': typeof ApiBrandingRouteWithChildren
  '/api/experiments': typeof ApiExperimentsRouteWithChildren
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/objects': typeof ApiObjectsRouteWithChildren
  '/api/relationships': typeof ApiRelationshipsRoute
  '/e/$experimentId': typeof EExperimentIdRouteWithChildren
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/experiments/$id': typeof AuthenticatedExperimentsIdRoute
  '/api/branding/upload-url': typeof ApiBrandingUploadUrlRoute
  '/api/experiments/$id': typeof ApiExperimentsIdRouteWithChildren
  '/api/objects/$id': typeof ApiObjectsIdRoute
  '/api/public/branding': typeof ApiPublicBrandingRoute
  '/experiments/': typeof AuthenticatedExperimentsIndexRoute
  '/e/$experimentId/': typeof EExperimentIdIndexRoute
  '/api/experiments/$id/close': typeof ApiExperimentsIdCloseRoute
  '/api/experiments/$id/duplicate': typeof ApiExperimentsIdDuplicateRoute
  '/api/experiments/$id/publish': typeof ApiExperimentsIdPublishRoute
  '/api/experiments/$id/results': typeof ApiExperimentsIdResultsRoute
  '/api/experiments/$id/sessions': typeof ApiExperimentsIdSessionsRoute
  '/api/experiments/$id/stimuli': typeof ApiExperimentsIdStimuliRouteWithChildren
  '/api/public/experiments/$id': typeof ApiPublicExperimentsIdRouteWithChildren
  '/api/public/sessions/$token': typeof ApiPublicSessionsTokenRouteWithChildren
  '/e/$experimentId/s/$token': typeof EExperimentIdSTokenRoute
  '/api/experiments/$id/stimuli/$stimulusId': typeof ApiExperimentsIdStimuliStimulusIdRoute
  '/api/experiments/$id/stimuli/upload-url': typeof ApiExperimentsIdStimuliUploadUrlRoute
  '/api/public/experiments/$id/sessions': typeof ApiPublicExperimentsIdSessionsRoute
  '/api/public/sessions/$token/complete': typeof ApiPublicSessionsTokenCompleteRoute
  '/api/public/sessions/$token/consent': typeof ApiPublicSessionsTokenConsentRoute
  '/api/public/sessions/$token/responses': typeof ApiPublicSessionsTokenResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system': typeof SystemRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/branding': typeof ApiBrandingRouteWithChildren
  '/api/experiments': typeof ApiExperimentsRouteWithChildren
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/objects': typeof ApiObjectsRouteWithChildren
  '/api/relationships': typeof ApiRelationshipsRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/experiments/$id': typeof AuthenticatedExperimentsIdRoute
  '/api/branding/upload-url': typeof ApiBrandingUploadUrlRoute
  '/api/experiments/$id': typeof ApiExperimentsIdRouteWithChildren
  '/api/objects/$id': typeof ApiObjectsIdRoute
  '/api/public/branding': typeof ApiPublicBrandingRoute
  '/experiments': typeof AuthenticatedExperimentsIndexRoute
  '/e/$experimentId': typeof EExperimentIdIndexRoute
  '/api/experiments/$id/close': typeof ApiExperimentsIdCloseRoute
  '/api/experiments/$id/duplicate': typeof ApiExperimentsIdDuplicateRoute
  '/api/experiments/$id/publish': typeof ApiExperimentsIdPublishRoute
  '/api/experiments/$id/results': typeof ApiExperimentsIdResultsRoute
  '/api/experiments/$id/sessions': typeof ApiExperimentsIdSessionsRoute
  '/api/experiments/$id/stimuli': typeof ApiExperimentsIdStimuliRouteWithChildren
  '/api/public/experiments/$id': typeof ApiPublicExperimentsIdRouteWithChildren
  '/api/public/sessions/$token': typeof ApiPublicSessionsTokenRouteWithChildren
  '/e/$experimentId/s/$token': typeof EExperimentIdSTokenRoute
  '/api/experiments/$id/stimuli/$stimulusId': typeof ApiExperimentsIdStimuliStimulusIdRoute
  '/api/experiments/$id/stimuli/upload-url': typeof ApiExperimentsIdStimuliUploadUrlRoute
  '/api/public/experiments/$id/sessions': typeof ApiPublicExperimentsIdSessionsRoute
  '/api/public/sessions/$token/complete': typeof ApiPublicSessionsTokenCompleteRoute
  '/api/public/sessions/$token/consent': typeof ApiPublicSessionsTokenConsentRoute
  '/api/public/sessions/$token/responses': typeof ApiPublicSessionsTokenResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/reset-password': typeof ResetPasswordRoute
  '/system': typeof SystemRoute
  '/_authenticated/experiments': typeof AuthenticatedExperimentsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/branding': typeof ApiBrandingRouteWithChildren
  '/api/experiments': typeof ApiExperimentsRouteWithChildren
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/objects': typeof ApiObjectsRouteWithChildren
  '/api/relationships': typeof ApiRelationshipsRoute
  '/e/$experimentId': typeof EExperimentIdRouteWithChildren
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/_authenticated/experiments/$id': typeof AuthenticatedExperimentsIdRoute
  '/api/branding/upload-url': typeof ApiBrandingUploadUrlRoute
  '/api/experiments/$id': typeof ApiExperimentsIdRouteWithChildren
  '/api/objects/$id': typeof ApiObjectsIdRoute
  '/api/public/branding': typeof ApiPublicBrandingRoute
  '/_authenticated/experiments/': typeof AuthenticatedExperimentsIndexRoute
  '/e/$experimentId/': typeof EExperimentIdIndexRoute
  '/api/experiments/$id/close': typeof ApiExperimentsIdCloseRoute
  '/api/experiments/$id/duplicate': typeof ApiExperimentsIdDuplicateRoute
  '/api/experiments/$id/publish': typeof ApiExperimentsIdPublishRoute
  '/api/experiments/$id/results': typeof ApiExperimentsIdResultsRoute
  '/api/experiments/$id/sessions': typeof ApiExperimentsIdSessionsRoute
  '/api/experiments/$id/stimuli': typeof ApiExperimentsIdStimuliRouteWithChildren
  '/api/public/experiments/$id': typeof ApiPublicExperimentsIdRouteWithChildren
  '/api/public/sessions/$token': typeof ApiPublicSessionsTokenRouteWithChildren
  '/e/$experimentId/s/$token': typeof EExperimentIdSTokenRoute
  '/api/experiments/$id/stimuli/$stimulusId': typeof ApiExperimentsIdStimuliStimulusIdRoute
  '/api/experiments/$id/stimuli/upload-url': typeof ApiExperimentsIdStimuliUploadUrlRoute
  '/api/public/experiments/$id/sessions': typeof ApiPublicExperimentsIdSessionsRoute
  '/api/public/sessions/$token/complete': typeof ApiPublicSessionsTokenCompleteRoute
  '/api/public/sessions/$token/consent': typeof ApiPublicSessionsTokenConsentRoute
  '/api/public/sessions/$token/responses': typeof ApiPublicSessionsTokenResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/explorer'
    | '/graph'
    | '/reset-password'
    | '/system'
    | '/experiments'
    | '/settings'
    | '/api/branding'
    | '/api/experiments'
    | '/api/graph'
    | '/api/health'
    | '/api/me'
    | '/api/objects'
    | '/api/relationships'
    | '/e/$experimentId'
    | '/objects/$id'
    | '/objects/new'
    | '/experiments/$id'
    | '/api/branding/upload-url'
    | '/api/experiments/$id'
    | '/api/objects/$id'
    | '/api/public/branding'
    | '/experiments/'
    | '/e/$experimentId/'
    | '/api/experiments/$id/close'
    | '/api/experiments/$id/duplicate'
    | '/api/experiments/$id/publish'
    | '/api/experiments/$id/results'
    | '/api/experiments/$id/sessions'
    | '/api/experiments/$id/stimuli'
    | '/api/public/experiments/$id'
    | '/api/public/sessions/$token'
    | '/e/$experimentId/s/$token'
    | '/api/experiments/$id/stimuli/$stimulusId'
    | '/api/experiments/$id/stimuli/upload-url'
    | '/api/public/experiments/$id/sessions'
    | '/api/public/sessions/$token/complete'
    | '/api/public/sessions/$token/consent'
    | '/api/public/sessions/$token/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/explorer'
    | '/graph'
    | '/reset-password'
    | '/system'
    | '/settings'
    | '/api/branding'
    | '/api/experiments'
    | '/api/graph'
    | '/api/health'
    | '/api/me'
    | '/api/objects'
    | '/api/relationships'
    | '/objects/$id'
    | '/objects/new'
    | '/experiments/$id'
    | '/api/branding/upload-url'
    | '/api/experiments/$id'
    | '/api/objects/$id'
    | '/api/public/branding'
    | '/experiments'
    | '/e/$experimentId'
    | '/api/experiments/$id/close'
    | '/api/experiments/$id/duplicate'
    | '/api/experiments/$id/publish'
    | '/api/experiments/$id/results'
    | '/api/experiments/$id/sessions'
    | '/api/experiments/$id/stimuli'
    | '/api/public/experiments/$id'
    | '/api/public/sessions/$token'
    | '/e/$experimentId/s/$token'
    | '/api/experiments/$id/stimuli/$stimulusId'
    | '/api/experiments/$id/stimuli/upload-url'
    | '/api/public/experiments/$id/sessions'
    | '/api/public/sessions/$token/complete'
    | '/api/public/sessions/$token/consent'
    | '/api/public/sessions/$token/responses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/discover'
    | '/explorer'
    | '/graph'
    | '/reset-password'
    | '/system'
    | '/_authenticated/experiments'
    | '/_authenticated/settings'
    | '/api/branding'
    | '/api/experiments'
    | '/api/graph'
    | '/api/health'
    | '/api/me'
    | '/api/objects'
    | '/api/relationships'
    | '/e/$experimentId'
    | '/objects/$id'
    | '/objects/new'
    | '/_authenticated/experiments/$id'
    | '/api/branding/upload-url'
    | '/api/experiments/$id'
    | '/api/objects/$id'
    | '/api/public/branding'
    | '/_authenticated/experiments/'
    | '/e/$experimentId/'
    | '/api/experiments/$id/close'
    | '/api/experiments/$id/duplicate'
    | '/api/experiments/$id/publish'
    | '/api/experiments/$id/results'
    | '/api/experiments/$id/sessions'
    | '/api/experiments/$id/stimuli'
    | '/api/public/experiments/$id'
    | '/api/public/sessions/$token'
    | '/e/$experimentId/s/$token'
    | '/api/experiments/$id/stimuli/$stimulusId'
    | '/api/experiments/$id/stimuli/upload-url'
    | '/api/public/experiments/$id/sessions'
    | '/api/public/sessions/$token/complete'
    | '/api/public/sessions/$token/consent'
    | '/api/public/sessions/$token/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  ExplorerRoute: typeof ExplorerRoute
  GraphRoute: typeof GraphRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SystemRoute: typeof SystemRoute
  ApiBrandingRoute: typeof ApiBrandingRouteWithChildren
  ApiExperimentsRoute: typeof ApiExperimentsRouteWithChildren
  ApiGraphRoute: typeof ApiGraphRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiObjectsRoute: typeof ApiObjectsRouteWithChildren
  ApiRelationshipsRoute: typeof ApiRelationshipsRoute
  EExperimentIdRoute: typeof EExperimentIdRouteWithChildren
  ObjectsIdRoute: typeof ObjectsIdRoute
  ObjectsNewRoute: typeof ObjectsNewRoute
  ApiPublicBrandingRoute: typeof ApiPublicBrandingRoute
  ApiPublicExperimentsIdRoute: typeof ApiPublicExperimentsIdRouteWithChildren
  ApiPublicSessionsTokenRoute: typeof ApiPublicSessionsTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/new': {
      id: '/objects/new'
      path: '/objects/new'
      fullPath: '/objects/new'
      preLoaderRoute: typeof ObjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id': {
      id: '/objects/$id'
      path: '/objects/$id'
      fullPath: '/objects/$id'
      preLoaderRoute: typeof ObjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$experimentId': {
      id: '/e/$experimentId'
      path: '/e/$experimentId'
      fullPath: '/e/$experimentId'
      preLoaderRoute: typeof EExperimentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relationships': {
      id: '/api/relationships'
      path: '/api/relationships'
      fullPath: '/api/relationships'
      preLoaderRoute: typeof ApiRelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objects': {
      id: '/api/objects'
      path: '/api/objects'
      fullPath: '/api/objects'
      preLoaderRoute: typeof ApiObjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph': {
      id: '/api/graph'
      path: '/api/graph'
      fullPath: '/api/graph'
      preLoaderRoute: typeof ApiGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiments': {
      id: '/api/experiments'
      path: '/api/experiments'
      fullPath: '/api/experiments'
      preLoaderRoute: typeof ApiExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/branding': {
      id: '/api/branding'
      path: '/api/branding'
      fullPath: '/api/branding'
      preLoaderRoute: typeof ApiBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments': {
      id: '/_authenticated/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AuthenticatedExperimentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/e/$experimentId/': {
      id: '/e/$experimentId/'
      path: '/'
      fullPath: '/e/$experimentId/'
      preLoaderRoute: typeof EExperimentIdIndexRouteImport
      parentRoute: typeof EExperimentIdRoute
    }
    '/_authenticated/experiments/': {
      id: '/_authenticated/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof AuthenticatedExperimentsIndexRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/api/public/branding': {
      id: '/api/public/branding'
      path: '/api/public/branding'
      fullPath: '/api/public/branding'
      preLoaderRoute: typeof ApiPublicBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objects/$id': {
      id: '/api/objects/$id'
      path: '/$id'
      fullPath: '/api/objects/$id'
      preLoaderRoute: typeof ApiObjectsIdRouteImport
      parentRoute: typeof ApiObjectsRoute
    }
    '/api/experiments/$id': {
      id: '/api/experiments/$id'
      path: '/$id'
      fullPath: '/api/experiments/$id'
      preLoaderRoute: typeof ApiExperimentsIdRouteImport
      parentRoute: typeof ApiExperimentsRoute
    }
    '/api/branding/upload-url': {
      id: '/api/branding/upload-url'
      path: '/upload-url'
      fullPath: '/api/branding/upload-url'
      preLoaderRoute: typeof ApiBrandingUploadUrlRouteImport
      parentRoute: typeof ApiBrandingRoute
    }
    '/_authenticated/experiments/$id': {
      id: '/_authenticated/experiments/$id'
      path: '/$id'
      fullPath: '/experiments/$id'
      preLoaderRoute: typeof AuthenticatedExperimentsIdRouteImport
      parentRoute: typeof AuthenticatedExperimentsRoute
    }
    '/e/$experimentId/s/$token': {
      id: '/e/$experimentId/s/$token'
      path: '/s/$token'
      fullPath: '/e/$experimentId/s/$token'
      preLoaderRoute: typeof EExperimentIdSTokenRouteImport
      parentRoute: typeof EExperimentIdRoute
    }
    '/api/public/sessions/$token': {
      id: '/api/public/sessions/$token'
      path: '/api/public/sessions/$token'
      fullPath: '/api/public/sessions/$token'
      preLoaderRoute: typeof ApiPublicSessionsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/experiments/$id': {
      id: '/api/public/experiments/$id'
      path: '/api/public/experiments/$id'
      fullPath: '/api/public/experiments/$id'
      preLoaderRoute: typeof ApiPublicExperimentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiments/$id/stimuli': {
      id: '/api/experiments/$id/stimuli'
      path: '/stimuli'
      fullPath: '/api/experiments/$id/stimuli'
      preLoaderRoute: typeof ApiExperimentsIdStimuliRouteImport
      parentRoute: typeof ApiExperimentsIdRoute
    }
    '/api/experiments/$id/sessions': {
      id: '/api/experiments/$id/sessions'
      path: '/sessions'
      fullPath: '/api/experiments/$id/sessions'
      preLoaderRoute: typeof ApiExperimentsIdSessionsRouteImport
      parentRoute: typeof ApiExperimentsIdRoute
    }
    '/api/experiments/$id/results': {
      id: '/api/experiments/$id/results'
      path: '/results'
      fullPath: '/api/experiments/$id/results'
      preLoaderRoute: typeof ApiExperimentsIdResultsRouteImport
      parentRoute: typeof ApiExperimentsIdRoute
    }
    '/api/experiments/$id/publish': {
      id: '/api/experiments/$id/publish'
      path: '/publish'
      fullPath: '/api/experiments/$id/publish'
      preLoaderRoute: typeof ApiExperimentsIdPublishRouteImport
      parentRoute: typeof ApiExperimentsIdRoute
    }
    '/api/experiments/$id/duplicate': {
      id: '/api/experiments/$id/duplicate'
      path: '/duplicate'
      fullPath: '/api/experiments/$id/duplicate'
      preLoaderRoute: typeof ApiExperimentsIdDuplicateRouteImport
      parentRoute: typeof ApiExperimentsIdRoute
    }
    '/api/experiments/$id/close': {
      id: '/api/experiments/$id/close'
      path: '/close'
      fullPath: '/api/experiments/$id/close'
      preLoaderRoute: typeof ApiExperimentsIdCloseRouteImport
      parentRoute: typeof ApiExperimentsIdRoute
    }
    '/api/public/sessions/$token/responses': {
      id: '/api/public/sessions/$token/responses'
      path: '/responses'
      fullPath: '/api/public/sessions/$token/responses'
      preLoaderRoute: typeof ApiPublicSessionsTokenResponsesRouteImport
      parentRoute: typeof ApiPublicSessionsTokenRoute
    }
    '/api/public/sessions/$token/consent': {
      id: '/api/public/sessions/$token/consent'
      path: '/consent'
      fullPath: '/api/public/sessions/$token/consent'
      preLoaderRoute: typeof ApiPublicSessionsTokenConsentRouteImport
      parentRoute: typeof ApiPublicSessionsTokenRoute
    }
    '/api/public/sessions/$token/complete': {
      id: '/api/public/sessions/$token/complete'
      path: '/complete'
      fullPath: '/api/public/sessions/$token/complete'
      preLoaderRoute: typeof ApiPublicSessionsTokenCompleteRouteImport
      parentRoute: typeof ApiPublicSessionsTokenRoute
    }
    '/api/public/experiments/$id/sessions': {
      id: '/api/public/experiments/$id/sessions'
      path: '/sessions'
      fullPath: '/api/public/experiments/$id/sessions'
      preLoaderRoute: typeof ApiPublicExperimentsIdSessionsRouteImport
      parentRoute: typeof ApiPublicExperimentsIdRoute
    }
    '/api/experiments/$id/stimuli/upload-url': {
      id: '/api/experiments/$id/stimuli/upload-url'
      path: '/upload-url'
      fullPath: '/api/experiments/$id/stimuli/upload-url'
      preLoaderRoute: typeof ApiExperimentsIdStimuliUploadUrlRouteImport
      parentRoute: typeof ApiExperimentsIdStimuliRoute
    }
    '/api/experiments/$id/stimuli/$stimulusId': {
      id: '/api/experiments/$id/stimuli/$stimulusId'
      path: '/$stimulusId'
      fullPath: '/api/experiments/$id/stimuli/$stimulusId'
      preLoaderRoute: typeof ApiExperimentsIdStimuliStimulusIdRouteImport
      parentRoute: typeof ApiExperimentsIdStimuliRoute
    }
  }
}

interface AuthenticatedExperimentsRouteChildren {
  AuthenticatedExperimentsIdRoute: typeof AuthenticatedExperimentsIdRoute
  AuthenticatedExperimentsIndexRoute: typeof AuthenticatedExperimentsIndexRoute
}

const AuthenticatedExperimentsRouteChildren: AuthenticatedExperimentsRouteChildren =
  {
    AuthenticatedExperimentsIdRoute: AuthenticatedExperimentsIdRoute,
    AuthenticatedExperimentsIndexRoute: AuthenticatedExperimentsIndexRoute,
  }

const AuthenticatedExperimentsRouteWithChildren =
  AuthenticatedExperimentsRoute._addFileChildren(
    AuthenticatedExperimentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExperimentsRoute: typeof AuthenticatedExperimentsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExperimentsRoute: AuthenticatedExperimentsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiBrandingRouteChildren {
  ApiBrandingUploadUrlRoute: typeof ApiBrandingUploadUrlRoute
}

const ApiBrandingRouteChildren: ApiBrandingRouteChildren = {
  ApiBrandingUploadUrlRoute: ApiBrandingUploadUrlRoute,
}

const ApiBrandingRouteWithChildren = ApiBrandingRoute._addFileChildren(
  ApiBrandingRouteChildren,
)

interface ApiExperimentsIdStimuliRouteChildren {
  ApiExperimentsIdStimuliStimulusIdRoute: typeof ApiExperimentsIdStimuliStimulusIdRoute
  ApiExperimentsIdStimuliUploadUrlRoute: typeof ApiExperimentsIdStimuliUploadUrlRoute
}

const ApiExperimentsIdStimuliRouteChildren: ApiExperimentsIdStimuliRouteChildren =
  {
    ApiExperimentsIdStimuliStimulusIdRoute:
      ApiExperimentsIdStimuliStimulusIdRoute,
    ApiExperimentsIdStimuliUploadUrlRoute:
      ApiExperimentsIdStimuliUploadUrlRoute,
  }

const ApiExperimentsIdStimuliRouteWithChildren =
  ApiExperimentsIdStimuliRoute._addFileChildren(
    ApiExperimentsIdStimuliRouteChildren,
  )

interface ApiExperimentsIdRouteChildren {
  ApiExperimentsIdCloseRoute: typeof ApiExperimentsIdCloseRoute
  ApiExperimentsIdDuplicateRoute: typeof ApiExperimentsIdDuplicateRoute
  ApiExperimentsIdPublishRoute: typeof ApiExperimentsIdPublishRoute
  ApiExperimentsIdResultsRoute: typeof ApiExperimentsIdResultsRoute
  ApiExperimentsIdSessionsRoute: typeof ApiExperimentsIdSessionsRoute
  ApiExperimentsIdStimuliRoute: typeof ApiExperimentsIdStimuliRouteWithChildren
}

const ApiExperimentsIdRouteChildren: ApiExperimentsIdRouteChildren = {
  ApiExperimentsIdCloseRoute: ApiExperimentsIdCloseRoute,
  ApiExperimentsIdDuplicateRoute: ApiExperimentsIdDuplicateRoute,
  ApiExperimentsIdPublishRoute: ApiExperimentsIdPublishRoute,
  ApiExperimentsIdResultsRoute: ApiExperimentsIdResultsRoute,
  ApiExperimentsIdSessionsRoute: ApiExperimentsIdSessionsRoute,
  ApiExperimentsIdStimuliRoute: ApiExperimentsIdStimuliRouteWithChildren,
}

const ApiExperimentsIdRouteWithChildren =
  ApiExperimentsIdRoute._addFileChildren(ApiExperimentsIdRouteChildren)

interface ApiExperimentsRouteChildren {
  ApiExperimentsIdRoute: typeof ApiExperimentsIdRouteWithChildren
}

const ApiExperimentsRouteChildren: ApiExperimentsRouteChildren = {
  ApiExperimentsIdRoute: ApiExperimentsIdRouteWithChildren,
}

const ApiExperimentsRouteWithChildren = ApiExperimentsRoute._addFileChildren(
  ApiExperimentsRouteChildren,
)

interface ApiObjectsRouteChildren {
  ApiObjectsIdRoute: typeof ApiObjectsIdRoute
}

const ApiObjectsRouteChildren: ApiObjectsRouteChildren = {
  ApiObjectsIdRoute: ApiObjectsIdRoute,
}

const ApiObjectsRouteWithChildren = ApiObjectsRoute._addFileChildren(
  ApiObjectsRouteChildren,
)

interface EExperimentIdRouteChildren {
  EExperimentIdIndexRoute: typeof EExperimentIdIndexRoute
  EExperimentIdSTokenRoute: typeof EExperimentIdSTokenRoute
}

const EExperimentIdRouteChildren: EExperimentIdRouteChildren = {
  EExperimentIdIndexRoute: EExperimentIdIndexRoute,
  EExperimentIdSTokenRoute: EExperimentIdSTokenRoute,
}

const EExperimentIdRouteWithChildren = EExperimentIdRoute._addFileChildren(
  EExperimentIdRouteChildren,
)

interface ApiPublicExperimentsIdRouteChildren {
  ApiPublicExperimentsIdSessionsRoute: typeof ApiPublicExperimentsIdSessionsRoute
}

const ApiPublicExperimentsIdRouteChildren: ApiPublicExperimentsIdRouteChildren =
  {
    ApiPublicExperimentsIdSessionsRoute: ApiPublicExperimentsIdSessionsRoute,
  }

const ApiPublicExperimentsIdRouteWithChildren =
  ApiPublicExperimentsIdRoute._addFileChildren(
    ApiPublicExperimentsIdRouteChildren,
  )

interface ApiPublicSessionsTokenRouteChildren {
  ApiPublicSessionsTokenCompleteRoute: typeof ApiPublicSessionsTokenCompleteRoute
  ApiPublicSessionsTokenConsentRoute: typeof ApiPublicSessionsTokenConsentRoute
  ApiPublicSessionsTokenResponsesRoute: typeof ApiPublicSessionsTokenResponsesRoute
}

const ApiPublicSessionsTokenRouteChildren: ApiPublicSessionsTokenRouteChildren =
  {
    ApiPublicSessionsTokenCompleteRoute: ApiPublicSessionsTokenCompleteRoute,
    ApiPublicSessionsTokenConsentRoute: ApiPublicSessionsTokenConsentRoute,
    ApiPublicSessionsTokenResponsesRoute: ApiPublicSessionsTokenResponsesRoute,
  }

const ApiPublicSessionsTokenRouteWithChildren =
  ApiPublicSessionsTokenRoute._addFileChildren(
    ApiPublicSessionsTokenRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  ExplorerRoute: ExplorerRoute,
  GraphRoute: GraphRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SystemRoute: SystemRoute,
  ApiBrandingRoute: ApiBrandingRouteWithChildren,
  ApiExperimentsRoute: ApiExperimentsRouteWithChildren,
  ApiGraphRoute: ApiGraphRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMeRoute: ApiMeRoute,
  ApiObjectsRoute: ApiObjectsRouteWithChildren,
  ApiRelationshipsRoute: ApiRelationshipsRoute,
  EExperimentIdRoute: EExperimentIdRouteWithChildren,
  ObjectsIdRoute: ObjectsIdRoute,
  ObjectsNewRoute: ObjectsNewRoute,
  ApiPublicBrandingRoute: ApiPublicBrandingRoute,
  ApiPublicExperimentsIdRoute: ApiPublicExperimentsIdRouteWithChildren,
  ApiPublicSessionsTokenRoute: ApiPublicSessionsTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
