/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectsNewRouteImport } from './routes/objects.new'
import { Route as ObjectsIdRouteImport } from './routes/objects.$id'
import { Route as ApiRelationshipsRouteImport } from './routes/api/relationships'
import { Route as ApiObjectsRouteImport } from './routes/api/objects'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGraphRouteImport } from './routes/api/graph'
import { Route as ApiObjectsIdRouteImport } from './routes/api/objects.$id'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsNewRoute = ObjectsNewRouteImport.update({
  id: '/objects/new',
  path: '/objects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdRoute = ObjectsIdRouteImport.update({
  id: '/objects/$id',
  path: '/objects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelationshipsRoute = ApiRelationshipsRouteImport.update({
  id: '/api/relationships',
  path: '/api/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObjectsRoute = ApiObjectsRouteImport.update({
  id: '/api/objects',
  path: '/api/objects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGraphRoute = ApiGraphRouteImport.update({
  id: '/api/graph',
  path: '/api/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObjectsIdRoute = ApiObjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiObjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/system': typeof SystemRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/objects': typeof ApiObjectsRouteWithChildren
  '/api/relationships': typeof ApiRelationshipsRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/api/objects/$id': typeof ApiObjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/system': typeof SystemRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/objects': typeof ApiObjectsRouteWithChildren
  '/api/relationships': typeof ApiRelationshipsRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/api/objects/$id': typeof ApiObjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explorer': typeof ExplorerRoute
  '/graph': typeof GraphRoute
  '/system': typeof SystemRoute
  '/api/graph': typeof ApiGraphRoute
  '/api/health': typeof ApiHealthRoute
  '/api/objects': typeof ApiObjectsRouteWithChildren
  '/api/relationships': typeof ApiRelationshipsRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/objects/new': typeof ObjectsNewRoute
  '/api/objects/$id': typeof ApiObjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/explorer'
    | '/graph'
    | '/system'
    | '/api/graph'
    | '/api/health'
    | '/api/objects'
    | '/api/relationships'
    | '/objects/$id'
    | '/objects/new'
    | '/api/objects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/explorer'
    | '/graph'
    | '/system'
    | '/api/graph'
    | '/api/health'
    | '/api/objects'
    | '/api/relationships'
    | '/objects/$id'
    | '/objects/new'
    | '/api/objects/$id'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/explorer'
    | '/graph'
    | '/system'
    | '/api/graph'
    | '/api/health'
    | '/api/objects'
    | '/api/relationships'
    | '/objects/$id'
    | '/objects/new'
    | '/api/objects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  ExplorerRoute: typeof ExplorerRoute
  GraphRoute: typeof GraphRoute
  SystemRoute: typeof SystemRoute
  ApiGraphRoute: typeof ApiGraphRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiObjectsRoute: typeof ApiObjectsRouteWithChildren
  ApiRelationshipsRoute: typeof ApiRelationshipsRoute
  ObjectsIdRoute: typeof ObjectsIdRoute
  ObjectsNewRoute: typeof ObjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/new': {
      id: '/objects/new'
      path: '/objects/new'
      fullPath: '/objects/new'
      preLoaderRoute: typeof ObjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id': {
      id: '/objects/$id'
      path: '/objects/$id'
      fullPath: '/objects/$id'
      preLoaderRoute: typeof ObjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relationships': {
      id: '/api/relationships'
      path: '/api/relationships'
      fullPath: '/api/relationships'
      preLoaderRoute: typeof ApiRelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objects': {
      id: '/api/objects'
      path: '/api/objects'
      fullPath: '/api/objects'
      preLoaderRoute: typeof ApiObjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/graph': {
      id: '/api/graph'
      path: '/api/graph'
      fullPath: '/api/graph'
      preLoaderRoute: typeof ApiGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objects/$id': {
      id: '/api/objects/$id'
      path: '/$id'
      fullPath: '/api/objects/$id'
      preLoaderRoute: typeof ApiObjectsIdRouteImport
      parentRoute: typeof ApiObjectsRoute
    }
  }
}

interface ApiObjectsRouteChildren {
  ApiObjectsIdRoute: typeof ApiObjectsIdRoute
}

const ApiObjectsRouteChildren: ApiObjectsRouteChildren = {
  ApiObjectsIdRoute: ApiObjectsIdRoute,
}

const ApiObjectsRouteWithChildren = ApiObjectsRoute._addFileChildren(
  ApiObjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  ExplorerRoute: ExplorerRoute,
  GraphRoute: GraphRoute,
  SystemRoute: SystemRoute,
  ApiGraphRoute: ApiGraphRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiObjectsRoute: ApiObjectsRouteWithChildren,
  ApiRelationshipsRoute: ApiRelationshipsRoute,
  ObjectsIdRoute: ObjectsIdRoute,
  ObjectsNewRoute: ObjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
